// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const authStorage =
  typeof window !== "undefined"
    ? window.sessionStorage
    : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use sessionStorage to minimize exposure of tokens via XSS vulnerabilities.
    // Fallback to undefined if executed in non-browser environments.
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
